const chalk = require('chalk')
const fs = require('fs')

global.animemenu = `✘ 『 Anime 』
⌕ .stickhandhold  
⌕ .stickshinobu  
⌕ .stickcuddle  
⌕ .stickhighfive  
⌕ .stickdance  
⌕ .stickcringe  
⌕ .stickhappy  
⌕ .stickglomp  
⌕ .sticksmug  
⌕ .stickblush  
⌕ .stickawoo  
⌕ .stickwave  
⌕ .sticksmile  
⌕ .stickslap  
⌕ .stickpoke  
⌕ .stickwink  
⌕ .stickbonk  
⌕ .stickbully  
⌕ .stickyeet  
⌕ .stickbike  
⌕ .stickkiss  
⌕ .sticklick  
⌕ .stickpat  
⌕ .stickhug  
⌕ .stickkill  
⌕ .stickcry  
⌕ .stickspank  
⌕ .sticktickle  
⌕ .traceanime  
⌕ .akira  
⌕ .akiyama  
⌕ .ana  
⌕ .asuna  
⌕ .ayuzawa  
⌕ .boruto  
⌕ .chiho  
⌕ .chitoge  
⌕ .cosplayloli  
⌕ .cosplaysagiri  
⌕ .deidara  
⌕ .doraemon  
⌕ .elaina  
⌕ .emilia  
⌕ .erza  
⌕ .gremory  
⌕ .hestia  
⌕ .husbu  
⌕ .inori  
⌕ .isuzu  
⌕ .itachi  
⌕ .itori  
⌕ .kaga  
⌕ .kagura  
⌕ .kakasih  
⌕ .kaori  
⌕ .keneki  
⌕ .kotori  
⌕ .kurumi  
⌕ .loli  
⌕ .loli2  
⌕ .madara  
⌕ .megumin  
⌕ .mikasa  
⌕ .mikey  
⌕ .miku  
⌕ .minato  
⌕ .naruto  
⌕ .neko  
⌕ .nekonime  
⌕ .nezuko  
⌕ .onepiece  
⌕ .pokemon  
⌕ .randomnime  
⌕ .randomnime2  
⌕ .rize  
⌕ .sagiri  
⌕ .sakura  
⌕ .sasuke  
⌕ .shina  
⌕ .shinka  
⌕ .shinomiya  
⌕ .shizuka  
⌕ .shota  
⌕ .tejina  
⌕ .toukachan  
⌕ .tsunade  
⌕ .waifu  
⌕ .waifu2  
⌕ .animewall  
⌕ .yotsuba  
⌕ .yuki  
⌕ .yulibocil  
⌕ .yumeko  
⌕ .8ball  
⌕ .feed  
⌕ .animeawoo  
⌕ .animemegumin  
⌕ .animeshinobu  
⌕ .animehandhold  
⌕ .animehighfive  
⌕ .animecringe  
⌕ .animedance  
⌕ .animehappy  
⌕ .animeglomp  
⌕ .animeblush  
⌕ .animesmug  
⌕ .animewave  
⌕ .animesmille  
⌕ .animepoke  
⌕ .animewink  
⌕ .animebonk  
⌕ .animebully  
⌕ .animeyeet  
⌕ .animebite  
⌕ .animelick  
⌕ .animekill  
⌕ .animecry  
⌕ .animewlp  
⌕ .animekiss  
⌕ .animehug  
⌕ .animeneko  
⌕ .animepat  
⌕ .animeslap  
⌕ .animecuddle  
⌕ .animewaifu  
⌕ .animenom  
⌕ .animefoxgirl  
⌕ .animegecg  
⌕ .animetickle  
⌕ .animefeed  
⌕ .animeavatar  
⌕ .anime  
⌕ .animequote  
⌕ .avatar  
⌕ .shinobu  
⌕ .fox_girl  
⌕ .gecg  
╰–––––––––––––––༓`

global.arielownermenu = `✘ 『 Owner Menu 』
⌕ .autoread  
⌕ .autobio  
⌕ .autotype  
⌕ .unavailable  
⌕ .autorecord  
⌕ .autorecordtype  
⌕ .autoswview  
⌕ .setautoblock  
⌕ .setantiforeign  
⌕ .autoblock  
⌕ .onlygc  
⌕ .onlypc  
⌕ .onlyindo  
⌕ .anticall  
⌕ .self  
⌕ .public  
⌕ .join  
⌕ .poll 
⌕ .spam  
⌕ .bc  
⌕ .bcgroup  
⌕ .setmenu  
⌕ .setimgmenu  
⌕ .setvidmenu  
⌕ .setgifmenu  
⌕ .setreply  
⌕ .setprefix  
⌕ .addlimit  
⌕ .dellimit  
⌕ .resethit  
⌕ .resetuser  
⌕ .creategc  
⌕ .userjid  
⌕ .setexif  
⌕ .setbotbio  
⌕ .delppbot  
⌕ .shutdown  
⌕ .setppbot  
⌕ .addowner  
⌕ .delowner  
⌕ .addvn  
⌕ .addapk  
⌕ .addzip  
⌕ .addpdf  
⌕ .delapk  
⌕ .delzip  
⌕ .delpdf  
⌕ .delvn  
⌕ .addsticker  
⌕ .delsticker  
⌕ .addimage  
⌕ .delimage  
⌕ .addvideo  
⌕ .delvideo  
⌕ .addtitle  
⌕ .deltitle  
⌕ .upswtext  
⌕ .upswvideo  
⌕ .upswimage  
⌕ .upswaudio  
⌕ .autosticker  
⌕ .block  
⌕ .unblock  
⌕ .leavegc  
⌕ .pushcontact  
⌕ .pushcontactv2  
⌕ .pushcontactv3  
⌕ .jpm  
⌕ .post  
⌕ .clearall  
⌕ .pinchat  
⌕ .unpinchat  
`

global.othermenu = `✘ 『 Other Menu 』
⌕ .update  
⌕ .ping  
⌕ .menu  
⌕ .myip  
⌕ .repo  
⌕ .reportbug  
⌕ .idgroup  
⌕ .owner  
⌕ .rentbot  
⌕ .donate  
⌕ .checkaccount  
⌕ .runtime  
`

global.downloadmenu = `✘ 『 Download Menu 』
⌕ .itunes  
⌕ .play  
⌕ .ytmp3
⌕ .ytsearch
⌕ .ytsearch2
⌕ .ytmp4  
⌕ .tiktok  
⌕ .tiktokaudio  
⌕ .tiktokvideo  
⌕ .tiktokslide  
⌕ .igvideo
⌕ .igimage  
⌕ .facebook  
⌕ .facebook2
⌕ .twitter  
⌕ .capcut  
⌕ .apk  
⌕ .mega  
⌕ .mediafire  
⌕ .google  
⌕ .gimage  
⌕ .weather  
⌕ .spotify  
⌕ .gitclone  
⌕ .happymod  
⌕ .gdrive  
⌕ .pinterest  
⌕ .ringtone  
⌕ .autodownload  
`

global.groupmenu = `✘ 『 Group Menu 』
⌕ .antibot  
⌕ .readviewonce  
⌕ .antiviewonce  
⌕ .welcome  
⌕ .adminevent  
⌕ .groupevent  
⌕ .antiforeign  
⌕ .antimedia  
⌕ .antiaudio  
⌕ .antivideo  
⌕ .antiimage  
⌕ .antidocument  
⌕ .antilocation  
⌕ .anticontact  
⌕ .antisticker  
⌕ .antipoll  
⌕ .antilink  
⌕ .antilinkgc  
⌕ .antipromotion  
⌕ .antivirtex  
⌕ .grouplink  
⌕ .listadmin  
⌕ .invite  
⌕ .ephemeral  
⌕ .delete  
⌕ .setppgroup  
⌕ .delppgroup  
⌕ .setnamegc  
⌕ .setdesc  
⌕ .add  
⌕ .kick  
⌕ .promote  
⌕ .demote  
⌕ .kickall  
⌕ .promoteall  
⌕ .demoteall  
⌕ .getcontact  
⌕ .savecontact  
⌕ .sendcontact  
⌕ .contactag  
⌕ .hidetag  
⌕ .totag  
⌕ .tagall  
⌕ .editinfo  
⌕ .opentime  
⌕ .closetime  
⌕ .resetlink  
⌕ .getbio  
⌕ .vote  
⌕ .upvote  
⌕ .downvote  
⌕ .checkvote  
⌕ .delvote  
⌕ .antivirus  
⌕ .antitoxic  
⌕ .react  
⌕ .getjoinrequest  
`

global.funmenu = `✘ 『 Fun Menu 』
⌕ .define  
⌕ .readmore  
⌕ .fact  
⌕ .couple  
⌕ .soulmate  
⌕ .stupidcheck  
⌕ .handsomecheck  
⌕ .uncleancheck  
⌕ .hotcheck  
⌕ .smartcheck  
⌕ .greatcheck  
⌕ .evilcheck  
⌕ .dogcheck  
⌕ .coolcheck  
⌕ .waifucheck  
⌕ .awesomecheck  
⌕ .gaycheck  
⌕ .cutecheck  
⌕ .lesbiancheck  
⌕ .hornycheck  
⌕ .prettycheck  
⌕ .lovelycheck  
⌕ .uglycheck  
⌕ .pick  
⌕ .pickupline  
⌕ .quotes  
⌕ .can  
⌕ .is  
⌕ .when  
⌕ .where  
⌕ .what  
⌕ .how  
⌕ .rate  
⌕ .cry  
⌕ .kill  
⌕ .hug  
⌕ .pat  
⌕ .lick   
⌕ .kiss  
⌕ .bite  
⌕ .yeet  
⌕ .bully  
⌕ .bonk  
⌕ .wink  
⌕ .poke  
⌕ .nom  
⌕ .slap  
⌕ .smile   
⌕ .wave  
⌕ .awoo  
⌕ .blush  
⌕ .smug  
⌕ .glomp   
⌕ .happy  
⌕ .dance  
⌕ .cringe ??
⌕ .cuddle  
⌕ .highfive   
⌕ .handhold  
⌕ .spank  
⌕ .tickle  
⌕ .feed  
⌕ .checkme  
⌕ .sound1 - sound161  
`

global.stalkermenu = `✘ 『 Stalker 』
⌕ .tiktokstalk  
⌕ .mlstalk  
⌕ .npmstalk  
⌕ .ghstalk  
`

global.stickermenu = `✘ 『 Sticker 』
⌕ .goose  
⌕ .woof  
⌕ .8ball  
⌕ .lizard  
⌕ .meow  
⌕ .gura  
⌕ .telestick  
⌕ .sticker
⌕ .ttp  
`

global.databasemenu = `✘ 『 Database 』
⌕ .setcmd  
⌕ .delcmd  
⌕ .listcmd  
⌕ .lockcmd  
⌕ .addmsg  
⌕ .delmsg  
⌕ .getmsg  
⌕ .listmsg  
`

global.storemenu = `✘ 『 Store 』
⌕ .list  
⌕ .store  
⌕ .shop  
⌕ .addlist  
⌕ .dellist  
`

global.aimenu = `✘ 『 OpenAI 』
⌕ .animate  
⌕ .diffusion-anime  
⌕ .bingai  
⌕ .blackboxai  
⌕ .travel-assistant  
⌕ .guru-ai  
⌕ .emi-ai  
⌕ .claude-ai  
⌕ .costume-ai  
⌕ .herc-ai  
⌕ .hercaiv1  
⌕ .hercai-cartoon  
⌕ .hercai-animefy  
⌕ .hercai-lexica  
⌕ .hercai-prodia  
⌕ .hercai-simurg  
⌕ .hercai-raava  
⌕ .hercai-shonin  
⌕ .realistic  
⌕ .3dmodel  
⌕ .openai-indo  
⌕ .indo-ai  
⌕ .diffusion  
⌕ .photoleap  
⌕ .openai  
⌕ .dalle  
⌕ .ai  
⌕ .remini  
⌕ .simi  
⌕ .removebg  
⌕ .tozombie  
⌕ .toanime  
`

global.bugmenu = `✘ 『 Bug & War 』
⌕ .areact  
⌕ .abug
⌕ .abug2  
⌕ .iosbug  
⌕ .iosbug2  
⌕ .aaudio  
⌕ .aaudio2  
⌕ .asticker  
⌕ .asticker2  
⌕ .aloc  
⌕ .aloc2  
⌕ .alist  
⌕ .alist2  
⌕ .tempban  
⌕ .xcrash  
⌕ .xcrash2  
⌕ .xioscrash  
⌕ .xioscrash2  
⌕ .iosgoogle  
⌕ .iosgoogle2  
⌕ .iosq  
⌕ .amountbug  
⌕ .pmbug  
⌕ .delaybug  
⌕ .docubug  
⌕ .unlimitedbug  
⌕ .bombug  
⌕ .lagbug  
⌕ .trollybug  
⌕ .gcbug  
⌕ .delaygcbug  
⌕ .laggcbug  
⌕ .bomgcbug  
⌕ .unlimitedgcbug  
⌕ .trollygcbug  
⌕ .docugcbug  
⌕ .verif  
⌕ .banv1  
⌕ .banv2  
⌕ .banv3  
⌕ .banv4  
⌕ .banv5  
⌕ .banv6  
⌕ .unbanv1  
⌕ .unbanv2  
⌕ .unbanv3  
⌕ .unbanv4  
⌕ .unbanv5  
`

global.randphotomenu = `✘ 『 Random Photo 』
⌕ .aesthetic  
⌕ .coffee  
⌕ .wikimedia  
⌕ .wallpaper  
⌕ .art  
⌕ .bts  
⌕ .dogwoof  
⌕ .catmeow  
⌕ .lizardpic  
⌕ .goosebird  
⌕ .8ballpool  
⌕ .cosplay  
⌕ .hacker  
⌕ .cyber  
⌕ .gamewallpaper  
⌕ .islamic  
⌕ .jennie  
⌕ .jiso  
⌕ .satanic  
⌕ .justina  
⌕ .cartoon  
⌕ .pentol  
⌕ .cat  
⌕ .kpop  
⌕ .exo  
⌕ .lisa  
⌕ .space  
⌕ .car  
⌕ .technology  
⌕ .bike  
⌕ .shortquote  
⌕ .antiwork  
⌕ .hacking  
⌕ .boneka  
⌕ .rose  
⌕ .ryujin  
⌕ .ulzzangboy  
⌕ .ulzzanggirl  
⌕ .wallml  
⌕ .wallphone  
⌕ .mountain  
⌕ .goose  
⌕ .profilepic  
⌕ .couplepp  
⌕ .programming  
⌕ .pubg  
⌕ .blackpink  
⌕ .randomboy    
⌕ .randomgirl  
⌕ .hijab    
⌕ .chinese  
⌕ .indo  
⌕ .japanese  
⌕ .korean  
⌕ .malay  
⌕ .thai  
⌕ .vietnamese  
`

global.gamemenu = `✘ 『 Game 』
⌕ .truth  
⌕ .dare  
⌕ .suit  
⌕ .tictactoe  
⌕ .math  
`

global.religionmenu = `✘ 『 Religon 』
⌕ .bible  
⌕ .quran  
⌕ .gita  
`

global.searchmenu = `✘ 『 Search 』
⌕ .google  
⌕ .wikipedia  
⌕ .ytsearch  
⌕ .xnxxsearch  
⌕ .xvideosearch  
⌕ .apksearch  
⌕ .stickersearch  
⌕ .imdb  
⌕ .wanumber  
⌕ .friend  
⌕ .lyrics  
`

global.convertmenu = `✘ 『 Convert 』
⌕ .obfuscate  
⌕ .styletext  
⌕ .fliptext  
⌕ .tts  
⌕ .say  
⌕ .togif  
⌕ .toqr  
⌕ .bass  
⌕ .blown  
⌕ .deep  
⌕ .earrape  
⌕ .fast  
⌕ .fat  
⌕ .nightcore  
⌕ .reverse  
⌕ .robot  
⌕ .slow  
⌕ .smooth  
⌕ .squirrel  
⌕ .tinyurl  
⌕ .tovn  
⌕ .toaudio  
⌕ .tomp3  
⌕ .tomp4 
⌕ .toimg  
⌕ .toonce  
⌕ .sticker  
⌕ .smeme  
⌕ .smeta  
⌕ .take  
⌕ .emoji  
⌕ .volaudio  
⌕ .volvideo  
⌕ .ebinary  
⌕ .dbinary  
⌕ .ssweb  
⌕ .quoted  
⌕ .translate  
`

global.listmenu = `✘ 『 List 』
⌕ .listprem  
⌕ .listowner  
⌕ .liststicker  
⌕ .listimage  
⌕ .listvideo  
⌕ .listvn  
⌕ .listapk  
⌕ .listzip  
⌕ .listpdf  
⌕ .listbadword  
⌕ .listpc  
⌕ .listgc 
`
global.randomphotomenu = ` ✘『 Random Photo 』
⌕ .aesthetic  
⌕ .coffee  
⌕ .wikimedia  
⌕ .wallpaper  
⌕ .art  
⌕ .bts  
⌕ .dogwoof  
⌕ .catmeow  
⌕ .lizardpic  
⌕ .goosebird  
⌕ .8ballpool  
⌕ .cosplay  
⌕ .hacker  
⌕ .cyber  
⌕ .gamewallpaper  
⌕ .islamic  
⌕ .jennie  
⌕ .jiso  
⌕ .satanic  
⌕ .justina  
⌕ .cartoon  
⌕ .pentol  
⌕ .cat  
⌕ .kpop  
⌕ .exo  
⌕ .lisa  
⌕ .space  
⌕ .car  
⌕ .technology  
⌕ .bike  
⌕ .shortquote  
⌕ .antiwork  
⌕ .hacking  
⌕ .boneka  
⌕ .rose  
⌕ .ryujin  
⌕ .ulzzangboy  
⌕ .ulzzanggirl  
⌕ .wallml  
⌕ .wallphone  
⌕ .mountain  
⌕ .goose  
⌕ .profilepic  
⌕ .couplepp  
⌕ .programming  
⌕ .pubg  
⌕ .blackpink  
⌕ .randomboy    
⌕ .randomgirl  
⌕ .hijab    
⌕ .chinese  
⌕ .indo  
⌕ .japanese  
⌕ .korean  
⌕ .malay  
⌕ .thai  
⌕ .vietnamese  `

let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update ${__filename}`))
	delete require.cache[file]
	require(file)
})